export const LIST_CUSTOMER = [
  {
    createdAt: 1648306792,
    fullName: 'Trần Thị Thuỷ',
    phone: '0984473489',
    email: 'thuytran@gmail.com',
    contentContact: 'Tôi Cần Xây dựng công trình thuỷ điện',
    address: 'Sa Pa, Lào Cai',
    IdCategory: '2',
    IdRegions: '1',
    id: '1',
  },
  {
    createdAt: 1648306732,
    fullName: 'Đỗ Văn Cường',
    phone: '0924748743',
    email: 'docuong@gmail.com',
    contentContact: 'Tôi cần xây biệt thự liền kề',
    address: 'Đan Phượng, Hà Nội',
    IdCategory: '9',
    IdRegions: '3',
    id: '2',
  },
  {
    createdAt: 1648306672,
    fullName: 'Lê Duy Tùng',
    phone: '0873464824',
    email: 'duytung@gmail.com',
    contentContact: '',
    address: 'Ba Vì, Hà Nội',
    IdCategory: '1',
    IdRegions: '3',
    id: '3',
  },
  {
    createdAt: 1648306612,
    fullName: 'Đinh công Long',
    phone: '0928387434',
    email: 'conglong@gmail.com',
    contentContact: '',
    address: 'Quận 10, Tp Hồ chí Minh',
    IdCategory: '9',
    IdRegions: '6',
    id: '4',
  },
  {
    createdAt: 1648306552,
    fullName: 'Nguyễn Đình Phú',
    phone: '0934837482',
    email: 'dinhphu@gmail.com',
    contentContact: '',
    address: 'Hồng Ngự, Đồng Tháp',
    IdCategory: '3',
    IdRegions: '5',
    id: '5',
  },
  {
    createdAt: 1648306492,
    fullName: 'Đỗ Xuân Thắng',
    phone: '0234898443',
    email: 'xuanthang@gmail.com',
    contentContact: '',
    address: 'Quận Sơn Trà, TP Đà Nẵng',
    IdCategory: '4',
    IdRegions: '5',
    id: '6',
  },
  {
    createdAt: 1648306432,
    fullName: 'Nông Đức Phong',
    phone: '0891834734',
    email: 'ducphong@gmail.com',
    contentContact: '',
    address: 'Chi Lăng, Lạng Sơn',
    IdCategory: '2',
    IdRegions: '4',
    id: '7',
  },
  {
    createdAt: 1648306372,
    fullName: 'Phan Văn Khải',
    phone: '0938438474',
    email: 'phankhai@gmail.com',
    contentContact: '',
    address: 'Tam Nông, Phú Thọ',
    IdCategory: '8',
    IdRegions: '3',
    id: '8',
  },
  {
    createdAt: 1648310546,
    fullName: 'Hoàng Anh Quân',
    phone: '0934834775',
    email: 'hoangquan@gmail.com',
    contentContact: '',
    address: 'Hà Đông, Hà Nội',
    IdCategory: '4',
    IdRegions: '3',
    id: '9',
  },
  {
    createdAt: 1648310486,
    fullName: 'Nguyễn Phương Thảo',
    phone: '0928844348',
    email: 'phuongthao@gmail.com',
    contentContact: '',
    address: 'Đống Đa, Hà Nội',
    IdCategory: '1',
    IdRegions: '3',
    id: '10',
  },
  {
    createdAt: 1648310426,
    fullName: 'Hồ Văn Hưng',
    phone: '09348875339',
    email: 'vanhung@gmail.com',
    contentContact: '',
    address: 'Quỳnh Lưu, Nghệ An',
    IdCategory: '5',
    IdRegions: '4',
    id: '11',
  },
  {
    createdAt: 1648310366,
    fullName: 'Nguyễn Anh Tú',
    phone: '0934829844',
    email: 'anhtu@gmail.com',
    contentContact: '',
    address: 'Nghi Sơn, Thanh Hoá',
    IdCategory: '6',
    IdRegions: '3',
    id: '12',
  },
  {
    createdAt: 1648310306,
    fullName: 'Nguyễn Minh Hiếu',
    phone: '0924884734',
    email: 'minhhieu@gmail.com',
    contentContact: '',
    address: 'Tây Hoà, Phú Yên',
    IdCategory: '5',
    IdRegions: '5',
    id: '13',
  },
  {
    createdAt: 1648310246,
    fullName: 'Nguyễn Trọng kiên',
    phone: '0848238499',
    email: 'trongkien@gmail.com',
    contentContact: '',
    address: 'Quận 1, TP Hồ Chí Minh',
    IdCategory: '8',
    IdRegions: '6',
    id: '14',
  },
  {
    createdAt: 1648310186,
    fullName: 'Hoàng Văn Giang',
    phone: '0395848575',
    email: 'hoanggiang@gmail.com',
    contentContact: '',
    address: 'TP Việt Trì, Phú Thọ',
    IdCategory: '9',
    IdRegions: '3',
    id: '15',
  },
  {
    createdAt: 1648310126,
    fullName: 'Ngô Tuấn Anh',
    phone: '0293488375',
    email: 'tuananh@gmail.com',
    contentContact: '',
    address: 'Long Biên, Hà Nội',
    IdCategory: '8',
    IdRegions: '3',
    id: '16',
  },
  {
    createdAt: 1648310066,
    fullName: 'Lê Thành',
    phone: '0934837583',
    email: 'lethanh@gmail.com',
    contentContact: '',
    address: 'Minh Hoá, Quảng Bình',
    IdCategory: '7',
    IdRegions: '4',
    id: '17',
  },
];
